apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-two-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: microservice-two-ui
  template:
    metadata:
      labels:
        app: microservice-two-ui
    spec:
      containers:
        - image: ashishrlad/main-simple-java-app:15896591780
          name: microservice-two-ui
          ports:
            - containerPort: 80
