apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-one-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: microservice-one-ui
  template:
    metadata:
      labels:
        app: microservice-one-ui
    spec:
      containers:
        - image: ashishrlad/microservice-one:master-16042472341
          name: microservice-one-ui
          ports:
            - containerPort: 80
